name: test
on:
  push: 
    branches: [master]

jobs:
  cicd-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repositório
        uses: actions/checkout@v2
        
      - name: Configurando ambiente
        uses: action/setup-python@v2
          with:
            python-version: 3.8
          
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Iniciar banco
        uses: superchange/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.0
      
      - name: Execução
        runs: |
          cd user_crud
          pytest
  
        
